auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /data
  storage:
    filesystem:
      chunks_directory: /data/chunks
      rules_directory: /data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 1h
  chunk_retain_period: 30m
  max_chunk_age: 2h
  chunk_target_size: 2097152

compactor:
  retention_enabled: true
  working_directory: /data/compactor
  delete_request_store: filesystem

limits_config:
  retention_period: 336h
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 40

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

analytics:
  reporting_enabled: false
