#- name: Setup nginx
#  ansible.builtin.include_tasks:
#    file: install-nginx.yml
- name: Setup domain
  ansible.builtin.include_tasks:
    file: setup-domain.yml

- name: Deploy website
  ansible.builtin.include_tasks:
    file: deploy-website.yml
