- name: Create a directory for the keycloak service
  ansible.builtin.file:
    path: /opt/{{domain}}/keycloak
    state: directory

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/{{domain}}/keycloak/docker-compose.yml
  register: docker_compose_yaml

- name: Template Env
  ansible.builtin.template:
    src: env.j2
    dest: /opt/{{domain}}/keycloak/.env
  register: env_template

- ansible.builtin.import_tasks: database.yml

- name: Pull the Images
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose pull"
    chdir: /opt/{{domain}}/keycloak
  when: docker_compose_yaml.changed

- name: Start the keycloak service with Docker Compose
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose up -d"
    chdir: /opt/{{domain}}/keycloak

- name: Restart on change
  when: docker_compose_yaml.changed or env_template.changed
  command:
    chdir: /opt/{{domain}}/keycloak
    cmd: "{{ docker_cli }} compose restart"
