services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    healthcheck:
#      test:  ["CMD-SHELL", "pg_isready", "-d", "postgres", "-u", "${POSTGRES_USER}"]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      postgres:

  pgadmin:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin4_container
    restart: always
    depends_on:
      - postgres
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    volumes:
      - ./pgadmin-data:/var/lib/
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      postgres:
  pgbackups:
    image: prodrigestivill/postgres-backup-local:17-alpine
    restart: always
   # user: postgres:postgres # Optional: see below
    volumes:
      - ./pgbackups:/backups
    networks:
      postgres:
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_CLUSTER=true
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - TZ=Europe/Berlin
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
  autorestic:
    image:  pascaliske/autorestic:latest
    restart: always
    environment:
      - RESTIC_HOST=postgres
    volumes:
      - ./autorestic/config.yml:/etc/autorestic/config.yml
      - ./pgbackups:/backups
      - ./autorestic/cron:/etc/cron/
    entrypoint: [ "/bin/sh", "/etc/cron/start_cron.sh" ]

networks:
  postgres:
