services:
  miniflux:
    image: miniflux/miniflux:2.3.0
    restart: always
    ports:
      - "8290:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LOG_LEVEL=info
      - LOG_DATE_TIME=1
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${MINIFLUX_ADMIN_USER}
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASSWORD}
      - METRICS_COLLECTOR=1
      - METRICS_ALLOWED_NETWORKS=0.0.0.0/0
      - POLLING_SCHEDULER=entry_frequency
      - SCHEDULER_ENTRY_FREQUENCY_MIN_INTERVAL=5
      - SCHEDULER_ENTRY_FREQUENCY_MAX_INTERVAL=1440
      - POLLING_FREQUENCY=30
      - BATCH_SIZE=50
      - BASE_URL=${MINIFLUX_URL}/miniflux
  db:
    image: postgres:18.4
    restart: always
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U miniflux -d miniflux" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgbackups:
    image: prodrigestivill/postgres-backup-local:18-alpine
    restart: always
    # user: postgres:postgres # Optional: see below
    volumes:
      - miniflux_pgbackups:/backups
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_CLUSTER=true
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - BACKUP_ON_START=TRUE
      - SCHEDULE=@daily
      - TZ=Europe/Berlin
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
  autorestic:
    image: pascaliske/autorestic:latest
    restart: always
    environment:
      - RESTIC_HOST=miniflux
    volumes:
      - ./autorestic/config.yml:/etc/autorestic/config.yml
      - ./autorestic/cron:/etc/cron/
      - miniflux-db:/backups/miniflux-db
      - miniflux_pgbackups:/backups/miniflux_pgbackups
    entrypoint: [ "/bin/sh", "/etc/cron/start_cron.sh" ]
volumes:
  miniflux-db:
  miniflux_pgbackups:
