- name: Setup User for the Monitor
  ansible.builtin.include_tasks:
    file: user-setup.yml

- name:               Upgrade all repositories
  apt:
    upgrade:          yes
    update_cache:     yes
    cache_valid_time: 3600
    autoclean:        yes
    autoremove:       yes
# https://help.divera247.com/pages/viewpage.action?pageId=119865769
- name: Install tools via apt
  apt:
    pkg:
      - libfuse2
      - dbus
      - notification-daemon
      - software-properties-common
      - prometheus-node-exporter # Systemmonitoring
    state: present
- name: Copy Files which are defining the service
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
    - /usr/share/dbus-1
    - /usr/share/dbus-1/services/
    - /home/monitor/.config
    - /home/monitor/.config/autostart
- name: Copy Notification Service
  ansible.builtin.copy:
    src: org.freedesktop.Notifications.service
    dest: /usr/share/dbus-1/services/org.freedesktop.Notifications.service
- name: Add contrib and non-free repositories
  ansible.builtin.command:
    cmd: "apt-add-repository -yn non-free"
  register: debian_repo
  changed_when: "'Adding component(s)' in repo_add.stdout"
- name: Update apt cache after adding repositories
  ansible.builtin.apt:
    update_cache: yes
  when: debian_repo.changed
- name: Install tools via apt
  apt:
    pkg:
      - libttspico-utils
      - vlc
      - xdotool

- name: Set architecture specific variables
  set_fact:
    arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'x86_64' }}"
- name: Download Divera Monitor App
  ansible.builtin.get_url:
    url: "https://s3.florian.divera247.de/public/software/monitor/DIVERA247-Monitor-{{monitor_version}}-{{arch}}.AppImage"
    dest: "/usr/local/bin/DIVERA247-Monitor-{{monitor_version}}-{{arch}}.AppImage"
    mode: '0755'
  register: monitor_app
- name: Create a symbolic link
  ansible.builtin.file:
    src: "/usr/local/bin/DIVERA247-Monitor-{{monitor_version}}-{{arch}}.AppImage"
    dest: /usr/local/bin/Monitor.AppImage
    owner: root
    group: root
    mode: '0755'
    state: link
- name: Copy Autostart for all users
  ansible.builtin.copy:
    src: divera.desktop
    dest: /etc/xdg/autostart/autostart/divera.desktop
    mode: 0777
    owner: monitor
- name: Reboot on Monitor App Update
  when: monitor_app.changed
  ansible.builtin.reboot:
    reboot_timeout: 300 # 5 Minuten, weil wir langsame Maschinen annehmen
- name: Setup User for the Monitor
  ansible.builtin.include_tasks:
    file: validate.yml
