# This is just an example! Please see available options to customize Navidrome for your needs at

# https://www.navidrome.org/docs/usage/configuration/options/#available-options

LogLevel = 'INFO'
TranscodingCacheSize = '200MiB'
MusicFolder = './music/Metal'
BaseUrl = '/navidrome'

# Scanner
Scanner.Schedule = '@every 3h'
# Scanner.PurgeMissing = "always"
Scanner.ScanOnStartup = "false"

# Sharing
EnableSharing = 'false'
DefaultShareExpiration = "8760h"

# Plugins
Plugins.Enabled = 'true'

Agents = 'listenbrainz,lastfm,deezer'

LastFM.Enabled = 'true'
LastFM.ApiKey = '{{lastfm_token_api_key}}'
LastFM.Secret = '{{lastfm_token_api_shared_secret}}'

Prometheus.Enabled = 'true'

# Prometheus.Password = 'TODO'

[Backup]
Path = "/backup"
Count = 7
Schedule =  "45 0 * * *"
