- name:               Upgrade all repositories
  apt:
    upgrade:          yes
    update_cache:     yes
    cache_valid_time: 3600
    autoclean:        yes
    autoremove:       yes

- name: Install tools via apt
  apt:
    pkg:
      - vim
      - git
      - restic
      - zsh
      - unattended-upgrades
    state: present

- name: Make sure we have all expected groups present
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - docker

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add the user
  ansible.builtin.user:
    name: triantium
    shell: /usr/bin/zsh
    append: true
    state: present
    groups:
      - docker
      - wheel
- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: triantium
    state: present
    key: https://github.com/triantium.keys

# // MAYBE chezmoi
# sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply $GITHUB_USERNAME
