- name: Create directories for the immich service
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ immich_data_dir }}"
    - "{{ immich_upload_location }}"
    - "{{ immich_db_data_location }}"
    - "{{ immich_data_dir }}/autorestic"
    - "{{ immich_data_dir }}/autorestic/cron"

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ immich_data_dir }}/docker-compose.yml"
  register: docker_compose_yaml

- name: Template Env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ immich_data_dir }}/.env"
  register: env_template

- name: Template Autorestic Config
  ansible.builtin.template:
    src: "{{ shared_templates_dir }}/autorestic/config.yml.j2"
    dest: "{{ immich_data_dir }}/autorestic/config.yml"
  register: autorestic_template

- name: Template Autorestic Crontab
  ansible.builtin.template:
    src: "{{ shared_templates_dir }}/autorestic/crontab.j2"
    dest: "{{ immich_data_dir }}/autorestic/cron/crontab"
  register: autorestic_crontab_template

- name: Copy Autorestic start_cron.sh
  ansible.builtin.template:
    src: "{{ shared_templates_dir }}/autorestic/start_cron.sh"
    dest: "{{ immich_data_dir }}/autorestic/cron/start_cron.sh"
  register: autorestic_start_cron_template

- name: Pull the Images
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose pull"
    chdir: "{{ immich_data_dir }}"
  when: docker_compose_yaml.changed

- name: Start the immich service with Docker Compose
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose up -d"
    chdir: "{{ immich_data_dir }}"

- name: Restart on change
  when: docker_compose_yaml.changed or env_template.changed or autorestic_template.changed or autorestic_crontab_template.changed or autorestic_start_cron_template.changed
  ansible.builtin.command:
    chdir: "{{ immich_data_dir }}"
    cmd: "{{ docker_cli }} compose restart"
