all:
  vars:
    ansible_become: True
development:
  hosts:
    berserker:
      ansible_become_password: "{{ lookup('community.general.passwordstore', ' hosts/berserker/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', ' hosts/berserker/login', subkey='login') }}"
    heimdall:
        ansible_become_password: "{{ lookup('community.general.passwordstore', ' hosts/heimdall/login') }}"
        ansible_user: "{{ lookup('community.general.passwordstore', ' hosts/heimdall/login', subkey='login') }}"
