{
 "title": "Octoprint",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(octoprint_infos_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Geschwindigkeit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(octoprint_x_travel_total [2m]) + rate(octoprint_y_travel_total [2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "octoprint_print_progress", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "targets": [
    { "expr": "octoprint_printer_state_info", "legendFormat": "{{state_id}}" }
   ]
  },
  {
   "title": "Druckbett",
   "type": "innius-video-panel",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cancelled Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "octoprint_cancelled_prints_total"
    }
   ]
  },
  {
   "title": "Failed Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "octoprint_failed_prints_total" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "octoprint_temperatures_target", "legendFormat": "target {{identifier}}" },
    { "expr": "octoprint_temperatures_actual", "legendFormat": "actual {{identifier}}" }
   ]
  },
  {
   "title": "Total Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "octoprint_done_prints_total" }
   ]
  }
 ]
}