{
 "title": "Spoolman",
 "description": "Summary dashboard for browsing filaments that exist in Spoolman when using Postgres",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vendor",
    "label": "vendor",
    "query": {
     "query": "label_values(spoolman_filament_info,vendor)"
    }
   },
   {
    "name": "material",
    "label": "material",
    "query": {
     "query": "label_values(spoolman_filament_info,material)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Verbleibendes Filament",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "expr": "spoolman_spool_initial_weight{} - spoolman_spool_weight_used{}",
     "legendFormat": "Spule {{spool_id}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Vendors",
   "type": "stat",
   "description": "Total vendors (filters applied)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (vendor) (spoolman_filament_info{vendor=~\"$vendor\",material=~\"$material\"}))",
     "legendFormat": "__auto",
     "rawSql": "SELECT COUNT(id) FROM vendor WHERE name IN ($vendor)"
    }
   ]
  },
  {
   "title": "Filaments",
   "type": "stat",
   "description": "All possible filaments (includes current filters)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (filament_id) (spoolman_filament_info{vendor=~\"$vendor\",material=~\"$material\"}))",
     "legendFormat": "__auto",
     "rawSql": "SELECT COUNT(filament.id) FROM filament \njoin vendor on filament.vendor_id = vendor.id\nwhere 1=1\n  and filament.material in ($material)\n  and vendor.name in ($vendor)\n"
    }
   ]
  },
  {
   "title": "Total Spools",
   "type": "stat",
   "description": "The total number of spools currently in stock. (includes filters0",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (spool_id) (spoolman_spool_initial_weight{}))",
     "legendFormat": "__auto",
     "rawSql": "SELECT COUNT(spool.id)\nFROM spool \njoin filament on filament.id = spool.filament_id\njoin vendor on filament.vendor_id = vendor.id\nwhere 1=1\n  and archived=false\n  and filament.material in ($material)\n  and vendor.name in ($vendor)"
    }
   ]
  },
  {
   "title": "Materials",
   "type": "stat",
   "description": "The total unique materials from all filaments",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (material) (spoolman_filament_info{vendor=~\"$vendor\",material=~\"$material\"}))",
     "legendFormat": "__auto",
     "rawSql": "select count(distinct(material))\nfrom filament\njoin vendor on vendor.id = filament.vendor_id\nwhere 1=1\n  and filament.material in ($material)\n  and vendor.name in ($vendor)"
    }
   ]
  }
 ]
}