{
 "title": "Syncthing",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Instanz",
    "query": {
     "query": "label_values(syncthing_events_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "syncthing_protocol_sent_bytes_total{instance=\"$server\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Recieved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "syncthing_protocol_recv_bytes_total{instance=\"$server\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Scanned Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "syncthing_scanner_scanned_items_total{instance=\"$server\"}",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "syncthing_events_total{instance=\"$server\",state=\"delivered\"}",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Folders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_model_folder_state{instance=\"$server\"}",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_connections_active{app=\"syncthing\",instance=\"$server\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}