services:
  server:
    image: gitea/gitea:1.26.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__SSH_PORT=222
      - GITEA__server__LISTEN_PORT=22
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=${GITEA__mailer__FROM}
      - GITEA__mailer__SMTP_PORT=${GITEA__mailer__SMTP_PORT:-587}
      - GITEA__mailer__PROTOCOL=${GITEA__mailer__PROTOCOL:-smtp+starttls}
      - GITEA__mailer__SMTP_ADDR=${GITEA__mailer__SMTP_ADDR}
      - GITEA__mailer__USER=${GITEA__mailer__USER}
      - GITEA__mailer__PASSWD=${GITEA__mailer__PASSWD}
    restart: always
    networks:
      - postgres-net
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
  autorestic:
    image: pascaliske/autorestic:latest
    restart: always
    environment:
      - RESTIC_HOST=gitea
    volumes:
      - ./autorestic/config.yml:/etc/autorestic/config.yml
      - ./autorestic/cron:/etc/cron/
      - gitea-data:/backups/gitea_data
    entrypoint: [ "/bin/sh", "/etc/cron/start_cron.sh" ]

volumes:
  gitea-data:

networks:
  postgres-net:
    external: true
