- name: Create a directory for the semaphore service
  ansible.builtin.file:
    path: "/opt/{{domain}}/semaphore"
    state: directory

- ansible.builtin.import_tasks: gpg.yml

- ansible.builtin.import_tasks: password-store.yml

- ansible.builtin.import_tasks: docker.yml

- ansible.builtin.import_tasks: database.yml

- ansible.builtin.import_tasks: deploy.yml
