- name: Create a directory for the influxdb service
  ansible.builtin.file:
    path: /opt//influxdb
    state: directory

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt//influxdb/docker-compose.yml
  register: docker_compose_yaml

- name: Start the influxdb service with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt//influxdb

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/monitoring-stack
    cmd: docker compose pull

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/monitoring-stack
    cmd: docker compose restart
