services:
  navidrome:
    image: deluan/navidrome:0.63.0
    user: 1001:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_CONFIGFILE: "/data/navidrome.toml"
      ND_MUSICFOLDER: "/music/Metal"
    volumes:
      - "${DATA_DIR}:/data"
      - "./backup:/backup"
      - "${MUSIC_DIR}:/music:ro"
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://localhost:4533/ping -O /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
