version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__SSH_PORT=222
      - GITEA__server__LISTEN_PORT=22
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=${GITEA__mailer__FROM}
      - GITEA__mailer__SMTP_PORT=${GITEA__mailer__SMTP_PORT:-587}
      - GITEA__mailer__PROTOCOL=${GITEA__mailer__PROTOCOL:-smtp+starttls}
      - GITEA__mailer__SMTP_ADDR=${GITEA__mailer__SMTP_ADDR}
      - GITEA__mailer__USER=${GITEA__mailer__USER}
      - GITEA__mailer__PASSWD=${GITEA__mailer__PASSWD}
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
        - POSTGRES_USER=gitea
        - POSTGRES_PASSWORD=gitea
        - POSTGRES_DB=gitea
    networks:
        - gitea
    volumes:
        - gitea-db:/var/lib/postgresql/data
volumes:
  gitea-data:
  gitea-db:
  # TODO Backup
