version: '3'

volumes:
  keycloak-data:
  keycloak-db:

services:
  postgres:
    image: 'postgres:16'
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    restart: 'always'
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres


  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    ports:
       - 8080:8080
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    entrypoint: ['/opt/keycloak/bin/kc.sh', 'start-dev']
    depends_on:
      - postgres
