sources:
  syslog:
    type: syslog
    address: 0.0.0.0:9000
    mode: tcp

  docker:
    # defaults to docker socket
    type: docker_logs

transforms:
  normalize_syslog:
    type: remap
    inputs:
      - syslog
    source: |
      .source_type = "syslog"

  normalize_docker:
    type: remap
    inputs:
      - docker
    source: |
      .source_type = "docker"

sinks:
  loki_syslog:
    type: loki
    inputs:
      - normalize_syslog
    endpoint: http://gloin.taila24d4b.ts.net:3100
    encoding:
      codec: json
    labels:
      source: syslog
      host: "{{ host }}"
      severity: "{{ severity }}"
      facility: "{{ facility }}"

  loki_docker:
    type: loki
    inputs:
      - normalize_docker
    endpoint: http://gloin.taila24d4b.ts.net:3100
    encoding:
      codec: json
    labels:
      source: docker
      host: "{{ host }}"
      container: "{{ container_name }}"
      image: "{{ image }}"
