- name: Create a directory for the postgres service
  ansible.builtin.file:
    path: /opt/postgres
    state: directory

- name: Create a directory for the postgres service
  ansible.builtin.file:
    path: "/opt/postgres/{{item}}"
    state: directory
  loop:
    - pgadmin4
    - pgbackups
    - pgadmin-data
    - postgres-data
    - autorestic

- name: Templating Environment
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/postgres/.env

- name: Template pgAdmin
  ansible.builtin.template:
    src: servers.json.j2
    dest: /opt/postgres/pgadmin4/servers.json

- name: Template Autorestic Config
  ansible.builtin.template:
    src: autorestic/config.yml.j2
    dest: /opt/postgres/autorestic/config.yml

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/postgres/docker-compose.yml
  register: docker_compose_yaml

- name: Start the postgres service with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/postgres

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/postgres
    cmd: docker compose pull

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/postgres
    cmd: docker compose restart
