- name: Create a directory for the postgres service
  ansible.builtin.file:
    path: "/opt/{{domain}}/postgres"
    state: directory

- name: Create a directory for the postgres service
  ansible.builtin.file:
    path: "/opt/{{domain}}/postgres/{{item}}"
    state: directory
  loop:
    - pgadmin4
    - autorestic
    - autorestic/cron

- name: Templating Environment
  ansible.builtin.template:
    src: env.j2
    dest: "/opt/{{domain}}/postgres/.env"

- name: Template pgAdmin
  ansible.builtin.template:
    src: servers.json.j2
    dest: "/opt/{{domain}}/postgres/pgadmin4/servers.json"

- name: Template Autorestic Crontab
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/crontab.j2"
    dest: "/opt/{{domain}}/postgres/autorestic/cron/crontab"

- name: Copy Autorestic start_cron.sh
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/start_cron.sh"
    dest: "/opt/{{domain}}/postgres/autorestic/cron/start_cron.sh"

- name: Template Autorestic Config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/config.yml.j2"
    dest: "/opt/{{domain}}/postgres/autorestic/config.yml"

- name: Create external Docker network
  ansible.builtin.command:
    cmd: "{{ docker_cli }} network create postgres-net"
  register: network_create
  changed_when: network_create.rc == 0
  failed_when: network_create.rc != 0 and 'already exists' not in network_create.stderr

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "/opt/{{domain}}/postgres/docker-compose.yml"
  register: docker_compose_yaml

- name: Start the postgres service with Docker Compose
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose up -d"
    chdir: "/opt/{{domain}}/postgres"

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: "/opt/{{domain}}/postgres"
    cmd: "{{ docker_cli }} compose pull"

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: "/opt/{{domain}}/postgres"
    cmd: "{{ docker_cli }} compose restart"
