
set $navidrome nas.fritz.box;

# reverse proxy

location /navidrome
{
  proxy_pass http://192.168.19.35:4533;
  include nginxconfig.io/proxy.conf;
  proxy_max_temp_file_size 0;
  proxy_set_header X-Forwarded-Proto https;
  proxy_redirect http:// https://;
}
