# reverse proxy
location /paperless {
	proxy_pass http://192.168.19.35:8085/paperless;
	include nginxconfig.io/proxy.conf;

	proxy_redirect off;
    add_header Referrer-Policy "strict-origin-when-cross-origin";
}
