upstream homeassistent
{
  keepalive 32; # keepalive connections
  server 192.168.19.35:8123; # homeassistant ip and port
}

# Required for Jenkins websocket agents
map $http_upgrade $connection_upgrade
{
  default upgrade;
  '' close;
}

server
{
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name triantium.ddns.net;
  root /var/www/triantium.ddns.net/public;

  # SSL
  ssl_certificate /etc/letsencrypt/live/triantium.ddns.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/triantium.ddns.net/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/triantium.ddns.net/chain.pem;

  # security
  include nginxconfig.io/security.conf;

  # index.html fallback
  location /
  {
    try_files $uri $uri/ /index.html;
  }

  include sites-available/restic.triantium.ddns.net.conf;
  include sites-available/navidrome.triantium.ddns.net.conf;
  include sites-available/miniflux.triantium.ddns.net.conf;
  include sites-available/paperless.triantium.ddns.net.conf;


#   location /api {
#       proxy_pass http://homeassistent/;
#       include nginxconfig.io/proxy.conf;
#    }

  # additional config
  include nginxconfig.io/general.conf;
}

server
{
  listen 8123 ssl http2;
  listen [::]:8123 ssl http2;

  server_name triantium.ddns.net;

  # SSL
  ssl_certificate /etc/letsencrypt/live/triantium.ddns.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/triantium.ddns.net/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/triantium.ddns.net/chain.pem;

  # security
  include nginxconfig.io/security.conf;

 location / {
    proxy_pass http://homeassistent/;
    include nginxconfig.io/proxy.conf;
 }
  # additional config
  include nginxconfig.io/general.conf;
}

# subdomains redirect
server
{
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name *.triantium.ddns.net;

  # SSL
  ssl_certificate /etc/letsencrypt/live/triantium.ddns.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/triantium.ddns.net/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/triantium.ddns.net/chain.pem;

  return 301 https://triantium.ddns.net$request_uri;
}

# HTTP redirect
server
{
  listen 80;
  listen [::]:80;

  server_name .triantium.ddns.net;

  include nginxconfig.io/letsencrypt.conf;

  location /
  {
    return 301 https://triantium.ddns.net$request_uri;
  }
}
