all:
  vars:
    ansible_become: True
production:
  hosts:
    nas:
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/nas/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/nas/login', subkey='login') }}"
    heimdall:
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/heimdall/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/heimdall/login', subkey='login') }}"
    octopi:
      ansible_become_password: "{{ lookup('community.general.passwordstore', ' hosts/octopi/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', ' hosts/octopi/login', subkey='login') }}"
divera:
  hosts:
    display-02:
      ansible_host: display-02.taila24d4b.ts.net
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/display-01/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/display-01/login', subkey='login') }}"
