- name: Create a directory for the semaphore service
  ansible.builtin.file:
    path: "/opt/{{domain}}/semaphore"
    state: directory

- name: Create a directory for the semaphore service
  ansible.builtin.file:
    path: "/opt/{{domain}}/semaphore/tailscale-state"
    state: directory

- ansible.builtin.import_tasks: gpg.yml

- ansible.builtin.import_tasks: password-store.yml

- ansible.builtin.import_tasks: ssh-key.yml

- ansible.builtin.import_tasks: docker.yml

- ansible.builtin.import_tasks: database.yml

- ansible.builtin.import_tasks: deploy.yml

- ansible.builtin.import_tasks: api-key.yml
