services:
  vector:
    image: timberio/vector:0.57.0-alpine
    container_name: vector
    restart: unless-stopped
    ports:
      - 9598:9598
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    healthcheck:
      test: ["CMD-SHELL", "pgrep vector || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
