- hosts: berserker
  tasks:
    - command: whoami
      register: whoami
    - debug:
        var: whoami.stdout
  roles:
#    - role: geerlingguy.pip
#    - role: geerlingguy.docker
    - role: docker-compose-pi-hole
#    - role: docker-compose-keycloak
#    - role: docker-compose-semaphore
