- hosts: heimdall
  tasks:
    - command: whoami
      register: whoami
    - debug:
        var: whoami.stdout
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: docker-compose-pi-hole
