- name: Create a directory for the pihole service
  ansible.builtin.file:
    path: /opt/pihole
    state: directory

- name: Copy Files which are defining the service
  ansible.builtin.file:
    path: "/opt/pihole/{{item}}"
    state: directory
  loop:
    - pihole
    - pihole/etc
    - autorestic
    - autorestic/cron

- name: Templating Environment
  ansible.builtin.template:
    src: env.j2
    dest: /opt/pihole/.env

- name: Copy dnsmasq
  ansible.builtin.copy:
    src: etc/dnsmasq.d/01-pihole.conf
    dest: /opt/pihole/pihole/etc

- name: Copy cron definition
  ansible.builtin.copy:
    src: cron
    dest: /opt/pihole/autorestic/

- name: Template Autorestic Config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /opt/pihole/autorestic/config.yml


- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/pihole/docker-compose.yml
  register: docker_compose_yaml

- name: Start the pihole service with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/pihole

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/pihole
    cmd: docker compose pull

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/pihole
    cmd: docker compose restart
