- name: Templating Environment
  ansible.builtin.template:
    src: env.j2
    dest: "/opt/{{domain}}/semaphore/.env"

- name: Template docker-compose.yml to target host
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/opt/{{domain}}/semaphore/docker-compose.yml"
  register: docker_compose_yaml

- name: Start the semaphore service with Docker Compose (build if missing)
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose up -d --build"
    chdir: "/opt/{{domain}}/semaphore"
