- name: Clone password store from git remote on target
  block:
    - name: Check if password store is a git repository
      ansible.builtin.stat:
        path: "{{ semaphore_pass_store_path }}/.git"
      register: pass_store_git

    - name: Remove non-git password store directory
      ansible.builtin.file:
        path: "{{ semaphore_pass_store_path }}"
        state: absent
      when: not pass_store_git.stat.exists

    - name: Ensure password store directory exists
      ansible.builtin.file:
        path: "{{ semaphore_pass_store_path }}"
        state: directory
        mode: '0755'

    - name: Add password store to git safe directories
      ansible.builtin.command:
        cmd: "git config --global --add safe.directory {{ semaphore_pass_store_path }}"
      register: git_safe_dir
      changed_when: false
      failed_when: false

    - name: Clone password store repository
      ansible.builtin.git:
        repo: "{{ semaphore_pass_store_repo }}"
        dest: "{{ semaphore_pass_store_path }}"
        accept_hostkey: true
        force: yes

    - name: Set ownership of password store directory to semaphore user (1001)
      ansible.builtin.file:
        path: "{{ semaphore_pass_store_path }}"
        owner: "1001"
        group: "1001"
        recurse: yes
