- name: Create a directory for the gitea service
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/{{domain}}/gitea
    - /opt/{{domain}}/gitea/autorestic
    - /opt/{{domain}}/gitea/autorestic/cron

- name: Template Autorestic Config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/config.yml.j2"
    dest: "/opt/{{domain}}/gitea/autorestic/config.yml"
  register: autorestic_template

- name: Template Autorestic Crontab
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/crontab.j2"
    dest: "/opt/{{domain}}/gitea/autorestic/cron/crontab"
  register: autorestic_crontab_template

- name: Copy Autorestic start_cron.sh
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/start_cron.sh"
    dest: "/opt/{{domain}}/gitea/autorestic/cron/start_cron.sh"
  register: autorestic_start_cron_template

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/{{domain}}/gitea/docker-compose.yml
  register: docker_compose_yaml

- name: Template Env
  ansible.builtin.template:
    src: env.j2
    dest: /opt/{{domain}}/gitea/.env
  register: env_template

- ansible.builtin.import_tasks: database.yml

- name: Pull the Images
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose pull"
    chdir: /opt/{{domain}}/gitea
  when: docker_compose_yaml.changed

- name: Start the gitea service with Docker Compose
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose up -d"
    chdir: /opt/{{domain}}/gitea

- name: Restart on change
  when: docker_compose_yaml.changed or env_template.changed or autorestic_template.changed or autorestic_crontab_template.changed or autorestic_start_cron_template.changed
  command:
    chdir: /opt/{{domain}}/gitea
    cmd: "{{ docker_cli }} compose restart"
