- name: Create a directory for the baby-buddy service
  ansible.builtin.file:
    path: /opt/baby-buddy
    state: directory

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/baby-buddy/docker-compose.yml
  register: docker_compose_yaml

- name: Start the baby-buddy service with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/baby-buddy

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/monitoring-stack
    cmd: docker compose pull

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/monitoring-stack
    cmd: docker compose restart
