- name: Create directories for the home-assistant service
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/opt/{{domain}}/home-assistant"
    - "/opt/{{domain}}/home-assistant/autorestic"
    - "/opt/{{domain}}/home-assistant/autorestic/cron"

- name: Template Autorestic Config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/config.yml.j2"
    dest: "/opt/{{domain}}/home-assistant/autorestic/config.yml"
  register: autorestic_template

- name: Template Autorestic Crontab
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/crontab.j2"
    dest: "/opt/{{domain}}/home-assistant/autorestic/cron/crontab"
  register: autorestic_crontab_template

- name: Copy Autorestic start_cron.sh
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../templates/autorestic/start_cron.sh"
    dest: "/opt/{{domain}}/home-assistant/autorestic/cron/start_cron.sh"
  register: autorestic_start_cron_template

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "/opt/{{domain}}/home-assistant/docker-compose.yml"
  register: docker_compose_yaml

- name: Pull on change
  when: docker_compose_yaml.changed
  ansible.builtin.command:
    chdir: "/opt/{{domain}}/home-assistant"
    cmd: "{{ docker_cli }} compose pull"

- name: Start the home-assistant service with Docker Compose
  ansible.builtin.command:
    cmd: "{{ docker_cli }} compose up -d"
    chdir: "/opt/{{domain}}/home-assistant"

- name: Restart on change
  when: docker_compose_yaml.changed or autorestic_template.changed or autorestic_crontab_template.changed or autorestic_start_cron_template.changed
  ansible.builtin.command:
    chdir: "/opt/{{domain}}/home-assistant"
    cmd: "{{ docker_cli }} compose restart"
