version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.25.1
    ports:
      - "9000:9000"
      - "9443:9443"
    environment: []
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
volumes:
  portainer-data:
