version: "3"
services:
  portainer-agent:
    image:  portainer/agent:2.28.1
    restart: always
    ports:
      - "9001:9001"
    environment: []
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
