all:
  vars:
    ansible_become: True
    docker_cli: /usr/bin/docker
pi:
  hosts:
    heimdall:
      ansible_host: heimdall.taila24d4b.ts.net
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/heimdall/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/heimdall/login', subkey='login') }}"
    gloin:
      ansible_host: gloin.taila24d4b.ts.net
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/gloin/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/gloin/login', subkey='login') }}"
#    inkycal:
#      ansible_host: inkycal.taila24d4b.ts.net
#      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/inkycal/login') }}"
#      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/inkycal/login', subkey='login') }}"
divera:
  vars:
    loki_endpoint: http://gloin.taila24d4b.ts.net:3100
  hosts:
    display-02:
      ansible_host: display-02.taila24d4b.ts.net
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/display-01/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/display-01/login', subkey='login') }}"
octoprint:
  hosts:
    octopi:
      ansible_host: octopi.taila24d4b.ts.net
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/octopi/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/octopi/login', subkey='login') }}"
qnap:
  hosts:
    nas.fritz.box:
      pass_alias: 'nas'
      ansible_python_interpreter: /opt/QPython312/bin/python3
      ansible_host: nas.taila24d4b.ts.net
      ansible_become: False
      docker_cli: /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'hosts/nas/login') }}"
      ansible_user: "{{ lookup('community.general.passwordstore', 'hosts/nas/login', subkey='login') }}"
