services:
  restic-exporter:
    image: ngosang/restic-exporter:2.1.2
    # privileged: true # because of a python call to time.time(); WTF
    # cap_add:
    #  - SYS_TIME is not sufficient
    environment:
      - TZ=Europe/Berlin
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - REFRESH_INTERVAL=3600 # 600 min # Takes at least 30min
    ports:
      - "8001:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://localhost:8001/metrics -O /dev/null"]
      interval: 60s
      timeout: 20s
      retries: 30
      start_period: 60s
