service_name: paperless-ngx
domain: triantium.ddns.net
paperless_url: https://{{ domain }}

admin_password_location: "services/paperless/{{ domain }}/admin"

paperless_admin_password: "{{ lookup('community.general.passwordstore', admin_password_location, missing='error') }}"
paperless_admin_user: "{{ lookup('community.general.passwordstore', admin_password_location,subkey='login' ,missing='error') }}"
paperless_admin_mail: "{{ lookup('community.general.passwordstore', admin_password_location,subkey='email' ,missing='error') }}"

exporter_password_location: "services/paperless/{{ domain }}/exporter"

paperless_exporter_password: "{{ lookup('community.general.passwordstore', exporter_password_location, missing='error') }}"
paperless_exporter_user: "{{ lookup('community.general.passwordstore', admin_password_location,subkey='login' ,missing='error') }}"

paperless_email_task_cron: '31 * * * *'
paperless_ocr_language: 'deu'

paperless_secret_key_location: "services/paperless/{{ domain }}/secret_key"
paperless_secret_key: "{{ lookup('community.general.passwordstore', paperless_secret_key_location, missing='error') }}"

autorestic_location_name: paperless-backups
autorestic_cron_minute: "{{ 60 | random(seed=inventory_hostname + '_' + service_name + '_cron_min') }}"
autorestic_cron_hour: "{{ 24 | random(seed=inventory_hostname + '_' + service_name + '_cron_hour') }}"
autorestic_cron: "{{ autorestic_cron_minute }} {{ autorestic_cron_hour }} * * *"
