- name: Create a directory for the keycloak service
  ansible.builtin.file:
    path: /opt/keycloak
    state: directory

- name: Create a directory for the keycloak service
  ansible.builtin.file:
    path: /opt/keycloak/{{uri}}
    state: directory

- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/keycloak/{{uri}}/docker-compose.yml
  register: docker_compose_yaml

- name: Start the keycloak service with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/keycloak/{{uri}}/

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/keycloak/{{uri}}/
    cmd: docker compose pull

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/keycloak/{{uri}}/
    cmd: docker compose restart
