version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9051" --address ":9050" /data

volumes:
  minio_storage: {}
