- hosts: gloin
  tasks:
    - command: whoami
      register: whoami
    - debug:
        var: whoami.stdout
  roles:
    #- role: common-setup
    #- role: geerlingguy.pip
    #- role: geerlingguy.docker
    - role: docker-compose-keycloak
    - role: docker-compose-vector
#    - role: docker-compose-semaphore
