- hosts:
   - pi
   - divera
  roles:
    - role: common-setup
    - role: geerlingguy.pip
    - role: geerlingguy.docker

- hosts: qnap
  roles:
    - role: docker-compose/docker-compose-node-exporter
    - role: docker-compose/docker-compose-postgres
    - role: docker-compose/docker-compose-navidrome
    - role: docker-compose/docker-compose-paperless-ngx
    - role: docker-compose/docker-compose-miniflux
    - role: docker-compose/docker-compose-gitea
    - role: docker-compose/docker-compose-home-assistant

- hosts: heimdall
  roles:
    - role: docker-compose-pi-hole

- hosts: gloin
  roles:
    - role: docker-compose/docker-compose-monitoring-stack
