- hosts:
   - pi
   - divera
  tasks:
    - name: Upgrade all repositories
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
        autoclean: yes
        autoremove: yes
