services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2026.5.4"
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # Bluetooth-support
    restart: unless-stopped
    privileged: true
    network_mode: host
  autorestic:
    image: pascaliske/autorestic:latest
    restart: always
    environment:
      - RESTIC_HOST=home-assistant
    volumes:
      - ./autorestic/config.yml:/etc/autorestic/config.yml
      - ./autorestic/cron:/etc/cron/
      - config:/backups/homeassistant_config
    entrypoint: [ "/bin/sh", "/etc/cron/start_cron.sh" ]

volumes:
  config:
